platform :ios,'10.0'
target 'LianbiHome' do
        pod 'UMCCommon'
        pod 'UMCSecurityPlugins'
        pod 'UMCShare/Social/DingDing'
        pod 'UMCShare/Social/ReducedWeChat'
        pod 'UMCShare/Social/ReducedQQ'
        pod 'UMCShare/UI'
        pod 'Masonry'
end
